# Generated by Django 4.1.3 on 2022-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1)),
                ('temp', models.CharField(choices=[('H', 'Hot'), ('I', 'Iced')], default='H', max_length=1)),
                ('flavor', models.CharField(choices=[('N', 'Caramel'), ('M', 'Mocha'), ('FV', 'French Vanilla'), ('N', 'None')], default='N', max_length=2)),
                ('dairy', models.CharField(choices=[('M', 'Milk'), ('C', 'Cream'), ('AM', 'Almond Milk'), ('OM', 'Oat Milk'), ('N', 'None')], default='N', max_length=2)),
                ('sweetener', models.CharField(choices=[('S', 'Sugar'), ('SPL', 'Splenda'), ('SNL', "Sweet 'n Low"), ('N', 'None')], default='N', max_length=3)),
            ],
        ),
    ]
