# Generated by Django 4.1.3 on 2022-11-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dairy',
            field=models.CharField(choices=[('Milk', 'Milk'), ('Cream', 'Cream'), ('Almond Milk', 'Almond Milk'), ('Oat Milk', 'Oat Milk'), ('N/A', 'None')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor',
            field=models.CharField(choices=[('Caramel', 'Caramel'), ('Mocha', 'Mocha'), ('French Vanilla', 'French Vanilla'), ('N/A', 'None')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='sweetener',
            field=models.CharField(choices=[('Sugar', 'Sugar'), ('Splenda', 'Splenda'), ("Sweet 'n Low", "Sweet 'n Low"), ('N/A', 'None')], default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='temp',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Iced', 'Iced')], default='Hot', max_length=15),
        ),
    ]
